# 1. Importing the libraries

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 2. Load the data

In [23]:
# Load the CSV file
# Keep this CSV file in the same folder as the notebook

df = pd.read_csv('retail_store_inventory.csv')

# Convert date column from text to date format
df['Date'] = pd.to_datetime(df['Date'])

# Display first 5 rows
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

# 3. Basic structure check

In [24]:
# Number of rows and columns
df.shape

(73100, 15)

In [25]:
# Column names
df.columns.tolist()

['Date',
 'Store ID',
 'Product ID',
 'Category',
 'Region',
 'Inventory Level',
 'Units Sold',
 'Units Ordered',
 'Demand Forecast',
 'Price',
 'Discount',
 'Weather Condition',
 'Holiday/Promotion',
 'Competitor Pricing',
 'Seasonality']

In [26]:
# Data types and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  datetime64[us]
 1   Store ID            73100 non-null  str
 2   Product ID          73100 non-null  str
 3   Category            73100 non-null  str
 4   Region              73100 non-null  str
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  str
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  str
dtypes: datetime64[us](1), float64(3), int64(5), str(6)
memory usage: 10.7 MB

In [27]:
# Random sample of rows
# This is often better than only checking the first 5 rows

df.sample(5, random_state=42)

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
66127,2023-10-24,S002,P0008,Electronics,North,225,138,144,139.31,40.47,0,Snowy,1,41.97,Winter
43485,2023-03-11,S005,P0006,Toys,North,200,105,119,117.55,18.65,15,Cloudy,1,16.65,Spring
34304,2022-12-10,S001,P0005,Clothing,East,145,70,137,78.51,20.33,15,Snowy,0,18.04,Winter
34317,2022-12-10,S001,P0018,Electronics,West,350,105,157,103.11,98.65,15,Sunny,0,95.43,Spring
38631,2023-01-22,S002,P0012,Groceries,North,145,76,145,92.47,10.04,20,Sunny,0,13.01,Winter

In [28]:
data_dictionary = pd.DataFrame({
    "column_name": df.columns,
    "data_type": df.dtypes.astype(str),
    "example_value": [df[col].dropna().iloc[0] if df[col].dropna().shape[0] > 0 else None for col in df.columns],
    "unique_values": [df[col].nunique() for col in df.columns]
})

data_dictionary

,column_name,data_type,example_value,unique_values
Date,Date,datetime64[us],2022-01-01 00:00:00,731
Store ID,Store ID,str,S001,5
Product ID,Product ID,str,P0001,20
Category,Category,str,Groceries,5
Region,Region,str,North,4
Inventory Level,Inventory Level,int64,231,451
Units Sold,Units Sold,int64,127,498
Units Ordered,Units Ordered,int64,55,181
Demand Forecast,Demand Forecast,float64,135.47,31608
Price,Price,float64,33.5,8999
Discount,Discount,int64,20,5
Weather Condition,Weather Condition,str,Rainy,4
Holiday/Promotion,Holiday/Promotion,int64,0,2
Competitor Pricing,Competitor Pricing,float64,29.69,9751
Seasonality,Seasonality,str,Autumn,4